{{- if .Values.githubApp.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-github-app
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.githubApp.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-github-app
    creationPolicy: Owner
  data:
  {{- range list "appId" "clientId" "clientSecret" "privateKey" }}
  - secretKey: {{ . }}
    remoteRef:
      key: {{ $.Values.githubApp.secretPath }}
      property: {{ . }}
  {{- end }}
{{- end }}
