{{- if .Values.githubAuth.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-github-auth
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.githubAuth.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-github-auth
    creationPolicy: Owner
  data:
  - secretKey: clientId
    remoteRef:
      key: {{ .Values.githubAuth.secretPath }}
      property: clientId
  - secretKey: clientSecret
    remoteRef:
      key: {{ .Values.githubAuth.secretPath }}
      property: clientSecret
{{- end }}
