{{- if .Values.github.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-github-credentials
  labels:
    app: {{ .Chart.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.github.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-github-credentials
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: {{ .Values.github.secretPath }}
      property: token
{{- end }}
